package aqueduct

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// ParseWorkflow reads a YAML file and returns a validated aqueduct.
func ParseWorkflow(path string) (*Workflow, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading workflow file: %w", err)
	}
	return ParseWorkflowBytes(data)
}

// ParseWorkflowBytes parses YAML bytes into a validated aqueduct.
func ParseWorkflowBytes(data []byte) (*Workflow, error) {
	var w Workflow
	if err := yaml.Unmarshal(data, &w); err != nil {
		return nil, fmt.Errorf("parsing workflow YAML: %w", err)
	}
	if err := Validate(&w); err != nil {
		return nil, err
	}
	return &w, nil
}

// ParseAqueductConfig reads a YAML file and returns a AqueductConfig.
func ParseAqueductConfig(path string) (*AqueductConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading cistern config: %w", err)
	}
	var cfg AqueductConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing cistern config YAML: %w", err)
	}
	if err := ValidateAqueductConfig(&cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}

// generatedHeader is prepended to generated instructions files.
const generatedHeader = "<!-- generated by ct cataractae generate — edit PERSONA.md and INSTRUCTIONS.md instead -->\n\n"

// GenerateCataractaeFiles writes instructions files for each unique agent identity
// referenced in the workflow's cataractae steps. The output filename is controlled
// by instructionsFile (e.g. "CLAUDE.md", "AGENTS.md", "GEMINI.md"); pass "" to
// default to "CLAUDE.md".
//
// Files are written to <cataractaeDir>/<identity>/<instructionsFile>.
// For each identity, PERSONA.md and INSTRUCTIONS.md must both exist; if either
// is missing, that identity is skipped without error.
//
// Backward compatibility: when instructionsFile differs from "CLAUDE.md" any
// pre-existing CLAUDE.md in the identity directory is left untouched — it may
// still be needed if users switch back to the claude provider.
func GenerateCataractaeFiles(w *Workflow, cataractaeDir string, instructionsFile string) ([]string, error) {
	if instructionsFile == "" {
		instructionsFile = "CLAUDE.md"
	}
	var written []string
	for _, identity := range w.UniqueIdentities() {
		dir := filepath.Join(cataractaeDir, identity)
		personaData, personaErr := os.ReadFile(filepath.Join(dir, "PERSONA.md"))
		if personaErr != nil {
			if os.IsNotExist(personaErr) {
				continue
			}
			return written, fmt.Errorf("read PERSONA.md for %s: %w", identity, personaErr)
		}
		instructionsData, instrErr := os.ReadFile(filepath.Join(dir, "INSTRUCTIONS.md"))
		if instrErr != nil {
			if os.IsNotExist(instrErr) {
				continue
			}
			return written, fmt.Errorf("read INSTRUCTIONS.md for %s: %w", identity, instrErr)
		}

		if err := os.MkdirAll(dir, 0o755); err != nil {
			return written, fmt.Errorf("create role dir %s: %w", dir, err)
		}

		persona := strings.TrimRight(string(personaData), "\n")
		instructions := strings.TrimRight(string(instructionsData), "\n")
		content := generatedHeader + persona + "\n\n" + instructions + "\n"

		path := filepath.Join(dir, instructionsFile)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return written, fmt.Errorf("write %s: %w", path, err)
		}
		written = append(written, path)

		posPath, err := writePipelinePositionFile(cataractaeDir, identity, w)
		if err != nil {
			return written, err
		}
		written = append(written, posPath)

		skillPath, err := injectProtocolSkill(cataractaeDir, identity)
		if err != nil {
			return written, err
		}
		if skillPath != "" {
			written = append(written, skillPath)
		}
	}
	return written, nil
}

// protocolSkillPathFn returns the path to the locally installed cataractae-protocol
// SKILL.md. Overridable in tests to avoid filesystem dependencies.
var protocolSkillPathFn = func() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".cistern", "skills", "cataractae-protocol", "SKILL.md")
}

// personaDescription extracts the first non-empty, non-heading line from PERSONA.md
// data that appears after the "# Role:" header. Falls back to TitleCaseName(identity)
// when no such line exists.
func personaDescription(data []byte, identity string) string {
	seenRole := false
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "# Role:") {
			seenRole = true
			continue
		}
		if !seenRole || trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		return trimmed
	}
	return TitleCaseName(identity)
}

// neighborLine returns "<name> — <description>" for a neighboring workflow step.
// The name is the step's identity, or step.Name when no identity is set.
// The description is read from the identity's PERSONA.md, falling back to TitleCaseName.
func neighborLine(step WorkflowCataractae, cataractaeDir string) string {
	if step.Identity == "" {
		return step.Name + " — " + TitleCaseName(step.Name)
	}
	data, err := os.ReadFile(filepath.Join(cataractaeDir, step.Identity, "PERSONA.md"))
	if err != nil {
		return step.Identity + " — " + TitleCaseName(step.Identity)
	}
	return step.Identity + " — " + personaDescription(data, step.Identity)
}

// writePipelinePositionFile writes PIPELINE_POSITION.md into <cataractaeDir>/<identity>/
// describing the identity's position in the workflow: predecessor and successor step.
func writePipelinePositionFile(cataractaeDir, identity string, w *Workflow) (string, error) {
	// Find the first step index that uses this identity.
	idx := -1
	for i, step := range w.Cataractae {
		if step.Identity == identity {
			idx = i
			break
		}
	}

	roleStep := WorkflowCataractae{Identity: identity}
	if idx >= 0 {
		roleStep = w.Cataractae[idx]
	}
	roleLine := neighborLine(roleStep, cataractaeDir)

	var predLine, succLine string

	if idx < 0 || idx == 0 {
		predLine = "none — you are first"
	} else {
		predLine = neighborLine(w.Cataractae[idx-1], cataractaeDir)
	}

	if idx < 0 || idx == len(w.Cataractae)-1 {
		succLine = "none — you are last"
	} else {
		succLine = neighborLine(w.Cataractae[idx+1], cataractaeDir)
	}

	content := "# Pipeline Position\n\n" +
		"- Your role: " + roleLine + "\n" +
		"- Predecessor: " + predLine + "\n" +
		"- Successor: " + succLine + "\n"

	path := filepath.Join(cataractaeDir, identity, "PIPELINE_POSITION.md")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("write PIPELINE_POSITION.md for %s: %w", identity, err)
	}
	return path, nil
}

// injectProtocolSkill copies the cataractae-protocol SKILL.md into
// <cataractaeDir>/<identity>/skills/cataractae-protocol/SKILL.md.
// Returns the destination path when copied; returns "", nil when the
// source is absent or empty (graceful skip for fresh environments).
func injectProtocolSkill(cataractaeDir, identity string) (string, error) {
	src := protocolSkillPathFn()
	if src == "" {
		return "", nil
	}
	data, err := os.ReadFile(src)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("read protocol skill: %w", err)
	}
	destDir := filepath.Join(cataractaeDir, identity, "skills", "cataractae-protocol")
	if err := os.MkdirAll(destDir, 0o755); err != nil {
		return "", fmt.Errorf("mkdir skill dir for %s: %w", identity, err)
	}
	dest := filepath.Join(destDir, "SKILL.md")
	if err := os.WriteFile(dest, data, 0o644); err != nil {
		return "", fmt.Errorf("write protocol skill for %s: %w", identity, err)
	}
	return dest, nil
}

// TitleCaseName converts a snake_case or kebab-case name to Title Case.
// "implementer" → "Implementer", "docs_writer" → "Docs Writer".
func TitleCaseName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool { return r == '_' || r == '-' })
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, " ")
}

// ScaffoldCataractaeDir creates PERSONA.md and INSTRUCTIONS.md template files in
// <cataractaeDir>/<name>/. Returns the paths to the created files.
// Returns an error if either file already exists.
func ScaffoldCataractaeDir(cataractaeDir, name string) (personaPath, instrPath string, err error) {
	dir := filepath.Join(cataractaeDir, name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", "", fmt.Errorf("create directory %s: %w", dir, err)
	}

	personaPath = filepath.Join(dir, "PERSONA.md")
	if _, statErr := os.Stat(personaPath); statErr == nil {
		return "", "", fmt.Errorf("PERSONA.md already exists at %s", personaPath)
	}
	if err := os.WriteFile(personaPath, []byte(cataractaePersonaTemplate(name)), 0o644); err != nil {
		return "", "", fmt.Errorf("write PERSONA.md: %w", err)
	}

	instrPath = filepath.Join(dir, "INSTRUCTIONS.md")
	if _, statErr := os.Stat(instrPath); statErr == nil {
		return "", "", fmt.Errorf("INSTRUCTIONS.md already exists at %s", instrPath)
	}
	if err := os.WriteFile(instrPath, []byte(cataractaeInstructionsTemplate()), 0o644); err != nil {
		return "", "", fmt.Errorf("write INSTRUCTIONS.md: %w", err)
	}

	return personaPath, instrPath, nil
}

func cataractaePersonaTemplate(name string) string {
	return fmt.Sprintf("# Role: %s\n\nTODO: Describe who this cataractae is and what makes them effective.\n", TitleCaseName(name))
}

func cataractaeInstructionsTemplate() string {
	return `## Protocol

1. **Read CONTEXT.md** before starting — note your droplet ID, requirements, and revision notes
2. **Complete your work**
3. **Signal outcome** — call one of:
   - ` + "`ct droplet pass <id> --notes \"...\"`" + `
   - ` + "`ct droplet recirculate <id> --notes \"...\"`" + `
   - ` + "`ct droplet pool <id> --notes \"...\"`" + `
`
}
