package aqueduct

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// ParseWorkflow reads a YAML file and returns a validated aqueduct.
func ParseWorkflow(path string) (*Workflow, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading workflow file: %w", err)
	}
	return ParseWorkflowBytes(data)
}

// ParseWorkflowBytes parses YAML bytes into a validated aqueduct.
func ParseWorkflowBytes(data []byte) (*Workflow, error) {
	var w Workflow
	if err := yaml.Unmarshal(data, &w); err != nil {
		return nil, fmt.Errorf("parsing workflow YAML: %w", err)
	}
	if err := Validate(&w); err != nil {
		return nil, err
	}
	return &w, nil
}

// ParseAqueductConfig reads a YAML file and returns a AqueductConfig.
func ParseAqueductConfig(path string) (*AqueductConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading farm config: %w", err)
	}
	var cfg AqueductConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing farm config YAML: %w", err)
	}
	if err := ValidateAqueductConfig(&cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}

// claudeGeneratedHeader is prepended to CLAUDE.md files generated from PERSONA.md + INSTRUCTIONS.md.
const claudeGeneratedHeader = "<!-- generated by ct cataractae generate — edit PERSONA.md and INSTRUCTIONS.md instead -->\n\n"

// GenerateCataractaeFiles writes CLAUDE.md files for each unique agent identity
// referenced in the workflow's cataractae steps.
// Files are written to <cataractaeDir>/<identity>/CLAUDE.md.
//
// For each identity, <cataractaeDir>/<identity>/PERSONA.md and INSTRUCTIONS.md must both
// exist. If either is missing, that identity is skipped.
func GenerateCataractaeFiles(w *Workflow, cataractaeDir string) ([]string, error) {
	var written []string
	for _, identity := range w.UniqueIdentities() {
		dir := filepath.Join(cataractaeDir, identity)
		personaData, personaErr := os.ReadFile(filepath.Join(dir, "PERSONA.md"))
		instructionsData, instrErr := os.ReadFile(filepath.Join(dir, "INSTRUCTIONS.md"))
		if personaErr != nil || instrErr != nil {
			continue
		}

		if err := os.MkdirAll(dir, 0o755); err != nil {
			return written, fmt.Errorf("create role dir %s: %w", dir, err)
		}

		persona := strings.TrimRight(string(personaData), "\n")
		instructions := strings.TrimRight(string(instructionsData), "\n")
		content := claudeGeneratedHeader + persona + "\n\n" + instructions + "\n"

		path := filepath.Join(dir, "CLAUDE.md")
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return written, fmt.Errorf("write %s: %w", path, err)
		}
		written = append(written, path)
	}
	return written, nil
}

// TitleCaseName converts a snake_case or kebab-case name to Title Case.
// "implementer" → "Implementer", "docs_writer" → "Docs Writer".
func TitleCaseName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool { return r == '_' || r == '-' })
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, " ")
}

// ScaffoldCataractaeDir creates PERSONA.md and INSTRUCTIONS.md template files in
// <cataractaeDir>/<name>/. Returns the paths to the created files.
// Returns an error if either file already exists.
func ScaffoldCataractaeDir(cataractaeDir, name string) (personaPath, instrPath string, err error) {
	dir := filepath.Join(cataractaeDir, name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", "", fmt.Errorf("create directory %s: %w", dir, err)
	}

	personaPath = filepath.Join(dir, "PERSONA.md")
	if _, statErr := os.Stat(personaPath); statErr == nil {
		return "", "", fmt.Errorf("PERSONA.md already exists at %s", personaPath)
	}
	if err := os.WriteFile(personaPath, []byte(cataractaePersonaTemplate(name)), 0o644); err != nil {
		return "", "", fmt.Errorf("write PERSONA.md: %w", err)
	}

	instrPath = filepath.Join(dir, "INSTRUCTIONS.md")
	if _, statErr := os.Stat(instrPath); statErr == nil {
		return "", "", fmt.Errorf("INSTRUCTIONS.md already exists at %s", instrPath)
	}
	if err := os.WriteFile(instrPath, []byte(cataractaeInstructionsTemplate()), 0o644); err != nil {
		return "", "", fmt.Errorf("write INSTRUCTIONS.md: %w", err)
	}

	return personaPath, instrPath, nil
}

func cataractaePersonaTemplate(name string) string {
	return fmt.Sprintf("# Role: %s\n\nTODO: Describe who this cataractae is and what makes them effective.\n", TitleCaseName(name))
}

func cataractaeInstructionsTemplate() string {
	return `## Protocol

1. **Read CONTEXT.md** before starting — note your droplet ID, requirements, and revision notes
2. **Complete your work**
3. **Signal outcome** — call one of:
   - ` + "`ct droplet pass <id> --notes \"...\"`" + `
   - ` + "`ct droplet recirculate <id> --notes \"...\"`" + `
   - ` + "`ct droplet block <id> --notes \"...\"`" + `
`
}

